### ISSUE TITLE
No firmware build instruction

### ISSUE THREAD

**Issue by svpcom** [night-ghost/minimosd-extra#124] opened 2016-01-18 10:13 UTC
There are no FW build instructions - i.e. how to build it from source? Also there no any makefiles

**Comment by night-ghost** [comment] 2016-01-28 18:43
errors in build caused by changes in the Arduino itself, bugreport was posted and accepted, ~ week ago the patch was committed to hourly build of Arduino

**Closed by night-ghost** 2016-01-28 18:43 UTC
